name: Build TTJJ

on:
  workflow_dispatch:  # 允许手动触发
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: homesmart
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # 步骤1：克隆 Gitee 私有仓库
      - name: Clone Gitee Repository
        run: |
          rm -rf TiantianFundApi
          git clone -b main --single-branch https://github.com/kouchao/TiantianFundApi

      # 步骤2：登录阿里云镜像仓库
      - name: Login to Aliyun Container Registry
        run: |
          echo ${{ secrets.ALIYUN_REPO_PASS }} | docker login \
            -u ${{ secrets.ALIYUN_REPO_USER }} \
            --password-stdin \
            ${{ secrets.ALIYUN_REPO_DOMAIN }}
            
      # 步骤3：构建并推送 Docker 镜像
      - name: Build and Push Docker Image
        working-directory: ./TiantianFundApi  # 进入代码目录
        run: |
          docker buildx version
          docker buildx create --use
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --platform linux/arm64 -t ${{ secrets.ALIYUN_REPO_DOMAIN }}/homesmart/ttfund:main-arm64 --push .
