name: Build and Push to Aliyun

on:
  workflow_dispatch:  # 允许手动触发
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ALY_REPO_NAMESPACE: homesmart
    steps:
      # 步骤1：克隆 Gitee 私有仓库
      - name: Clone Gitee Repository
        run: |
          git clone https://"${{ secrets.GITEE_USERNAME }}":"${{ secrets.GITEE_ACCESS_TOKEN }}"@gitee.com/"${{ secrets.GITEE_USERNAME_REPO }}"/"${{ secrets.GITEE_LOCALSERVE }}".git
          ls -la ${{ secrets.GITEE_LOCALSERVE }}  # 验证克隆结果

      # 步骤2：登录阿里云镜像仓库
      - name: Login to Aliyun Container Registry
        run: |
          echo ${{ secrets.ALIYUN_REPO_PASS }} | docker login \
            -u ${{ secrets.ALIYUN_REPO_USER }} \
            --password-stdin \
            registry.cn-hangzhou.aliyuncs.com

      # 步骤3：构建并推送 Docker 镜像
      - name: Build and Push Docker Image
        working-directory: ./[仓库名称]  # 进入代码目录
        run: |
          docker build -t ${{ secrets.ALIYUN_REPO_DOMAIN }}/homesmart/localserver:$GITHUB_SHA .
          docker push registry.cn-hangzhou.aliyuncs.com/homesmart/localserver:$GITHUB_SHA
