name: Build and Push to Aliyun

on:
  workflow_dispatch:  # 允许手动触发
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      NAMESPACE: homesmart
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # 步骤1：克隆 Gitee 私有仓库
      - name: Clone Gitee Repository
        run: |
          rm -rf ${{ secrets.GITEE_REPO_LOCALSERVE }}
          git clone -b home-projects --single-branch https://"${{ secrets.GITEE_USERNAME_REPO }}":"${{ secrets.GITEE_PASS_LOGIN }}"@gitee.com/"${{ secrets.GITEE_USERNAME_REPO }}"/"${{ secrets.GITEE_REPO_LOCALSERVE }}".git
          ls -la ${{ secrets.GITEE_REPO_LOCALSERVE }}  # 验证克隆结果

      # 步骤2：登录阿里云镜像仓库
      - name: Login to Aliyun Container Registry
        run: |
          echo ${{ secrets.ALIYUN_REPO_PASS }} | docker login \
            -u ${{ secrets.ALIYUN_REPO_USER }} \
            --password-stdin \
            ${{ secrets.ALIYUN_REPO_DOMAIN }}
            
      # 步骤3：构建并推送 Docker 镜像
      - name: Build and Push Docker Image
        working-directory: ./${{ secrets.GITEE_REPO_LOCALSERVE }}/home-projects/localserve  # 进入代码目录
        run: |
          docker build -t ${{ secrets.ALIYUN_REPO_DOMAIN }}/homesmart/localserver:debug .
          docker push ${{ secrets.ALIYUN_REPO_DOMAIN }}/homesmart/localserver:debug
      


