name: Pull Docker Image and Release to Gitee

on:
  schedule:
    - cron: '0 0 * * *'  # 每天定时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  pull-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: |
          docker pull linuxserver/nginx:1.26.3

      - name: Save Docker image to tar
        run: |
          docker save linuxserver/nginx:1.26.3 -o linuxserver_nginx.tar

      - name: Compress Docker image
        run: gzip linuxserver_nginx.tar
        
      - name: Get current date for tag
        id: get_date_tag
        run: |
          # 获取当前日期，格式为 YYYYMMDD
          current_date=$(date +'%Y%m%d')
          echo "Current date as tag: $current_date"
          echo "tag_name=$current_date" >> $GITHUB_ENV
        
      - name: Test create release
        id: create_release
        uses: nicennnnnnnlee/action-gitee-release@v1.0.5
        with:
          gitee_owner: gemilk
          gitee_repo: image_repo
          gitee_token: ${{ secrets.GITEE_ACCESS_TOKEN  }}
          gitee_tag_name:  ${{ env.tag_name }}
          gitee_release_name: ${{ env.tag_name }}
          gitee_release_body: 已同步
          gitee_target_commitish: master

            
      - name: Test upload file to exist release
        uses: nicennnnnnnlee/action-gitee-release@v1.0.5
        with:
          gitee_owner: gemilk
          gitee_repo: image_repo
          gitee_token: ${{ secrets.GITEE_ACCESS_TOKEN }}
          gitee_release_id: ${{ steps.create_release.outputs.release-id }}
          gitee_upload_retry_times:  3
          gitee_files: |
              linuxserver_nginx.tar.gz



