name: Pull Docker Image and Release to Gitee

on:
  schedule:
    - cron: '0 0 * * *'  # 每天定时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  pull-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: |
          docker pull linuxserver/nginx:1.26.3

      - name: Save Docker image to tar
        run: |
          docker save linuxserver/nginx:1.26.3 -o linuxserver_nginx.tar

      - name: Create Gitee Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITEE_ACCESS_TOKEN }}" \
            -d "tag_name=v1.1" \
            -d "name=Release Name" \
            -d "body=This is the release body." \
            -d "target_commitish=master" \
            "https://gitee.com/api/v5/repos/gemilk/image_repo/releases?access_token=${{ secrets.GITEE_ACCESS_TOKEN }}" || true  # 如果已存在，跳过

      - name: Upload docker image to Gitee release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITEE_ACCESS_TOKEN }}" \
            -F "attachment=@linuxserver_nginx.tar" \
            "https://gitee.com/api/v5/repos/gemilk/image_repo/releases/assets?access_token=${{ secrets.GITEE_ACCESS_TOKEN }}&tag_name=v1.0"


