name: Pull Docker Image and Release to Gitee

on:
  schedule:
    - cron: '0 0 * * *'  # 每天定时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  pull-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: |
          docker pull linuxserver/nginx:1.26.3

      - name: Save Docker image to tar
        run: |
          docker save linuxserver/nginx:1.26.3 -o linuxserver_nginx.tar

      - name: Create Release and save ID
        run: |
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITEE_ACCESS_TOKEN }}" \
            -d "tag_name=v1.2" \
            -d "name=nginx-release" \
            -d "body=Nginx docker image release" \
            -d "target_commitish=master" \
            "https://gitee.com/api/v5/repos/gemilk/image_repo/releases?access_token=${{ secrets.GITEE_ACCESS_TOKEN }}" > release.json || echo "Release may already exist"

      - name: Get release ID
        id: get_release_id
        run: |
          RELEASE_ID=$(jq -r .id release.json)
          echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV

      - name: Upload Docker image to Gitee Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITEE_ACCESS_TOKEN }}" \
            -F "attachment=@linuxserver_nginx.tar" \
            "https://gitee.com/api/v5/repos/gemilk/image_repo/releases/${{ env.RELEASE_ID }}/attachments?access_token=${{ secrets.GITEE_ACCESS_TOKEN }}"



