name: Self docker images repo

on:
  # schedule:
    # - cron: '0 0 * * 1'  # 每周一 00:00 UTC
  workflow_dispatch:  # 允许手动触发

jobs:
  pull-and-release:
    runs-on: ubuntu-latest
    
    env:
      NAMESPACE: homesmart

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Registry
        run: |
          docker login --username=${{ secrets.ALIYUN_REPO_USER }} ${{ secrets.ALIYUN_REPO_DOMAIN }} --password=${{ secrets.ALIYUN_REPO_PASS }}
      
      - name: Pull multiple Docker images
        run: |  
          process_image() {
            local image_name=$1
            local platform=${2:-"amd64"}  # 设置默认平台为amd64
            
            echo "Processing image: ${image_name} with platform: ${platform}"
            
            docker pull --platform "${platform}" "${image_name}"
            image_id=$(docker images --format "{{.ID}}" --filter "reference=${image_name}")
            modify_name=$(echo "${image_name}" | sed 's/\//-/g')
            if [[ "$platform" == "arm64" ]]; then
              modify_name="${modify_name}-arm64"
            fi
            docker tag "$image_id" "${{ secrets.ALIYUN_REPO_DOMAIN }}/${{ env.NAMESPACE }}/${modify_name}"
            docker push "${{ secrets.ALIYUN_REPO_DOMAIN }}/${{ env.NAMESPACE }}/${modify_name}"
          }

          # 登录Docker registry
          docker login --username="${{ secrets.ALIYUN_REPO_USER }}" "${{ secrets.ALIYUN_REPO_DOMAIN }}" --password="${{ secrets.ALIYUN_REPO_PASS }}"

          # 
          process_image "linuxserver/calibre-web:latest"
          
          # portainer
          process_image "portainer/portainer-ce:latest"

          # derp
          process_image "shadowofgost/derper:main"
          process_image "shadowofgost/derper:ip"
          # hs
          process_image "headscale/headscale:stable"
          # hs-ui 
          process_image "ghcr.io/gurucomputing/headscale-ui:latest"
          process_image "goodieshq/headscale-admin:latest"
          
          # ts
          process_image "tailscale/tailscale:stable"
          process_image "tailscale/tailscale:stable" "arm64"


          
          # nginx
          process_image "linuxserver/nginx:latest"
          process_image "linuxserver/nginx:latest" "arm64"
          
          # qb
          process_image "linuxserver/qbittorrent:latest"
          process_image "linuxserver/qbittorrent:latest" "arm64"

          # fb
          process_image "filebrowser/filebrowser:v2-s6"
          process_image "filebrowser/filebrowser:v2-s6" "arm64"

          # ha
          process_image "linuxserver/homeassistant:latest"
          process_image "linuxserver/homeassistant:latest" "arm64"
          
          # ha china
          process_image "hacn/hacn:stable"
          process_image "hacn/hacn:stable" "arm64"
          
          # frpc
          process_image "snowdreamtech/frpc:latest"
          process_image "snowdreamtech/frpc:latest" "arm64"
          
          # frps
          process_image "snowdreamtech/frps:latest"
          process_image "snowdreamtech/frps:latest" "arm64"
