
name: Self docker images repo

on:
  # schedule:
    # - cron: '0 0 * * 1'  # 每周一 00:00 UTC
  workflow_dispatch:  # 允许手动触发

jobs:
  pull-and-release:
    runs-on: ubuntu-latest
    
    env:
      GITEE_OWNER: gemilk
      GITEE_REPO: image_repo
      GITEE_RELEASE_TAG: docker-images

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull multiple Docker images
        run: |
          docker pull shadowofgost/derper:main
          docker pull shadowofgost/derper:ip
          docker pull tailscale/tailscale:stable
          docker login --username=${{ secrets.ALIYUN_REPO_USER }} ${{ secrets.ALIYUN_REPO_DOMAIN }} --password=${{ secrets.ALIYUN_REPO_PASS }}
          docker images
          image_id=$(docker images --format "{{.ID}}" --filter "reference=shadowofgost/derper:main")
          echo $image_id
          docker tag $image_id ${{ secrets.ALIYUN_REPO_DOMAIN }}/homesmart/shadowofgost/derper:main
          docker images
          docker push ${{ secrets.ALIYUN_REPO_DOMAIN }}/homesmart/shadowofgost/derper:main
          
         

      


      

      

