name: Self docker images repo

on:
  # schedule:
    # - cron: '0 0 * * 1'  # 每周一 00:00 UTC
  workflow_dispatch:  # 允许手动触发

jobs:
  pull-and-release:
    runs-on: ubuntu-latest
    
    env:
      NAMESPACE: homesmart

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull multiple Docker images
        run: |
          docker login --username=${{ secrets.ALIYUN_REPO_USER }} ${{ secrets.ALIYUN_REPO_DOMAIN }} --password=${{ secrets.ALIYUN_REPO_PASS }}
          
          # derp 
          derp_main="shadowofgost/derper:main"
          docker pull "${derp_main}"
          image_id=$(docker images --format "{{.ID}}" --filter "reference=${derp_main}")

          mod=$(echo "${derp_main}" | sed 's/\//-/g')
          docker tag $image_id ${{ secrets.ALIYUN_REPO_DOMAIN }}/${{ env.NAMESPACE }}/${mod}
          docker push ${{ secrets.ALIYUN_REPO_DOMAIN }}/${{ env.NAMESPACE }}/${mod}
